package com.google.android.android.common.package_9.internal;

import com.google.android.android.common.internal.zzbp;
import com.google.android.android.common.package_9.PendingResult.zza;
import com.google.android.android.common.package_9.ResultCallback;
import com.google.android.android.common.package_9.ResultTransform;
import com.google.android.android.common.package_9.Status;
import com.google.android.android.common.package_9.TransformedResult;
import com.google.android.gms.common.api.PendingResult;
import java.util.concurrent.TimeUnit;

public final class zzcu<R extends com.google.android.gms.common.api.Result>
  extends PendingResult<R>
{
  public final Status mStatus;
  
  public zzcu(Status paramStatus)
  {
    zzbp.get(paramStatus, "Status must not be null");
    zzbp.get(paramStatus.isSuccess() ^ true, "Status must not be success");
    mStatus = paramStatus;
  }
  
  public final com.google.android.android.common.package_9.Result await()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final com.google.android.android.common.package_9.Result await(long paramLong, TimeUnit paramTimeUnit)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final void cancel()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final Status getStatus()
  {
    return mStatus;
  }
  
  public final boolean isCanceled()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final void set(PendingResult.zza paramZza)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final void setResultCallback(ResultCallback paramResultCallback)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final void setResultCallback(ResultCallback paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final TransformedResult then(ResultTransform paramResultTransform)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final Integer zzafs()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
}
