package support.android.view;

import android.os.Build.VERSION;
import android.support.constraint.ConstraintLayout.LayoutParams;
import android.view.ViewGroup.LayoutParams;
import android.view.ViewGroup.MarginLayoutParams;

public class Item
{
  public static final int ID_NONE = -1;
  public int a = -1;
  public int activity = -1;
  public int b = -1;
  public int buffer = -1;
  public int c = -1;
  public float channel = 0.0F;
  public int client = -1;
  public int color = -1;
  public float context = 0.0F;
  public int count = -1;
  public int current = -1;
  public boolean d = false;
  public int data = -1;
  public boolean date = false;
  public int description = -1;
  public int e = -1;
  public int f = -1;
  public int flags = -1;
  public int g = -1;
  public int h = -1;
  public int height;
  public float i = -1.0F;
  public int id = -1;
  public int index = -1;
  public int j = -1;
  public int k = -1;
  public int key = -1;
  public int length = -1;
  public float level = 1.0F;
  public float line = 0.0F;
  public int m = -1;
  public int min = -1;
  public int n = -1;
  public float name = 0.0F;
  public int next = -1;
  public float offset = 0.0F;
  public int p = -1;
  public int parent = -1;
  public float path = 1.0F;
  public int position = -1;
  public int q;
  public int r;
  public int s = -1;
  public int size = 0;
  public float start = 0.0F;
  public int state = 0;
  public int status = -1;
  public int t = -1;
  public float text = 1.0F;
  public float time = 0.0F;
  public float title = 0.0F;
  public int type = -1;
  public float u = 0.5F;
  public int v = -1;
  public float value = 0.0F;
  public int version = 0;
  public float w = 0.5F;
  public float width = 0.0F;
  public int x = -1;
  public int y = -1;
  public String z = null;
  
  public Item() {}
  
  private void init(int paramInt, ConstraintLayout.LayoutParams paramLayoutParams)
  {
    height = paramInt;
    k = k;
    j = j;
    g = wrap;
    v = mode;
    n = n;
    e = e;
    b = d;
    f = f;
    c = c;
    color = color;
    count = count;
    s = limit;
    y = z;
    u = y;
    w = w;
    z = data;
    flags = flags;
    min = min;
    a = b;
    i = i;
    h = h;
    m = m;
    r = width;
    q = height;
    p = leftMargin;
    t = rightMargin;
    key = topMargin;
    type = bottomMargin;
    name = title;
    context = context;
    state = state;
    version = version;
    description = description;
    status = max;
    activity = index;
    client = key;
    parent = current;
    buffer = buffer;
    paramInt = Build.VERSION.SDK_INT;
    x = paramLayoutParams.getMarginEnd();
    position = paramLayoutParams.getMarginStart();
  }
  
  public Item clone()
  {
    Item localItem = new Item();
    d = d;
    r = r;
    q = q;
    h = h;
    m = m;
    i = i;
    k = k;
    j = j;
    g = g;
    v = v;
    n = n;
    e = e;
    b = b;
    f = f;
    c = c;
    color = color;
    count = count;
    s = s;
    y = y;
    u = u;
    w = w;
    z = z;
    flags = flags;
    min = min;
    u = u;
    u = u;
    u = u;
    u = u;
    u = u;
    a = a;
    p = p;
    t = t;
    key = key;
    type = type;
    x = x;
    position = position;
    size = size;
    id = id;
    current = current;
    index = index;
    length = length;
    data = data;
    next = next;
    name = name;
    context = context;
    version = version;
    state = state;
    path = path;
    date = date;
    title = title;
    channel = channel;
    time = time;
    level = level;
    text = text;
    line = line;
    offset = offset;
    value = value;
    width = width;
    start = start;
    description = description;
    status = status;
    activity = activity;
    client = client;
    parent = parent;
    buffer = buffer;
    return localItem;
  }
  
  public void init(ConstraintLayout.LayoutParams paramLayoutParams)
  {
    k = k;
    j = j;
    wrap = g;
    mode = v;
    n = n;
    e = e;
    d = b;
    f = f;
    c = c;
    color = color;
    count = count;
    limit = s;
    z = y;
    leftMargin = p;
    rightMargin = t;
    topMargin = key;
    bottomMargin = type;
    v = next;
    t = data;
    y = u;
    w = w;
    data = z;
    flags = flags;
    min = min;
    title = name;
    context = context;
    state = state;
    version = version;
    description = description;
    max = status;
    index = activity;
    key = client;
    current = parent;
    buffer = buffer;
    b = a;
    i = i;
    h = h;
    m = m;
    width = r;
    height = q;
    int i1 = Build.VERSION.SDK_INT;
    paramLayoutParams.setMarginStart(position);
    paramLayoutParams.setMarginEnd(x);
    paramLayoutParams.add();
  }
}
